language: python
python:
  - "3.6"
sudo: required
services:
  - docker
before_install:
  - docker build -t crccheck/gallery-cms .
# Only package we need is for codecov.io
install: pip install codecov
script:
  - docker run --rm -v ${PWD}:/app:rw crccheck/gallery-cms make clean test
after_success:
  - codecov
